### ISSUE TITLE
Orca build process has changed from autogen to Meson

### ISSUE THREAD

**Issue by masonasons** [RastislavKish/umai#1]
The script will not run upon Gnome/Orca 46 release unless modified to support the new Meson build sysem. Not urgent, just making sure you are aware :)

**Comment by RastislavKish** [comment]
Hello @Brynify,

thanks for the notice. Yes, it is indeed better to be safe than sorry. We have discussed the new build system on Orca's mailing list and in fact found that Ubuntu requires one additional linking step in addition to the official build instructions in order to make them work, so it seems UMAI will be again a help in fighting confusion.

Although, in the meantime, we should be safe as the script uses Gnome-44 branch for UM22.04 and Gnome-45 for everything else, this decision was made back in times when Orca was implementing the new keyhandling system in the main branch, and things were rather broken at the time. Now these issues seem to be already sorted out, so UMAI will likely switch to the main branch again for Ubuntu Mate 24.04, which is coming soon.

I will keep this issue open as a reminder until this switch is implemented, in case anyone was playing with the code.
